// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Olbrasoft.GitHub.Issues.Data.EntityFrameworkCore;

#nullable disable

namespace Olbrasoft.GitHub.Issues.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(GitHubDbContext))]
    [Migration("20251211113355_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "assigned"
                        },
                        new
                        {
                            Id = 2,
                            Name = "automatic_base_change_failed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "automatic_base_change_succeeded"
                        },
                        new
                        {
                            Id = 4,
                            Name = "base_ref_changed"
                        },
                        new
                        {
                            Id = 5,
                            Name = "closed"
                        },
                        new
                        {
                            Id = 6,
                            Name = "commented"
                        },
                        new
                        {
                            Id = 7,
                            Name = "committed"
                        },
                        new
                        {
                            Id = 8,
                            Name = "connected"
                        },
                        new
                        {
                            Id = 9,
                            Name = "convert_to_draft"
                        },
                        new
                        {
                            Id = 10,
                            Name = "converted_to_discussion"
                        },
                        new
                        {
                            Id = 11,
                            Name = "cross-referenced"
                        },
                        new
                        {
                            Id = 12,
                            Name = "demilestoned"
                        },
                        new
                        {
                            Id = 13,
                            Name = "deployed"
                        },
                        new
                        {
                            Id = 14,
                            Name = "deployment_environment_changed"
                        },
                        new
                        {
                            Id = 15,
                            Name = "disconnected"
                        },
                        new
                        {
                            Id = 16,
                            Name = "head_ref_deleted"
                        },
                        new
                        {
                            Id = 17,
                            Name = "head_ref_restored"
                        },
                        new
                        {
                            Id = 18,
                            Name = "head_ref_force_pushed"
                        },
                        new
                        {
                            Id = 19,
                            Name = "labeled"
                        },
                        new
                        {
                            Id = 20,
                            Name = "locked"
                        },
                        new
                        {
                            Id = 21,
                            Name = "mentioned"
                        },
                        new
                        {
                            Id = 22,
                            Name = "marked_as_duplicate"
                        },
                        new
                        {
                            Id = 23,
                            Name = "merged"
                        },
                        new
                        {
                            Id = 24,
                            Name = "milestoned"
                        },
                        new
                        {
                            Id = 25,
                            Name = "pinned"
                        },
                        new
                        {
                            Id = 26,
                            Name = "ready_for_review"
                        },
                        new
                        {
                            Id = 27,
                            Name = "referenced"
                        },
                        new
                        {
                            Id = 28,
                            Name = "renamed"
                        },
                        new
                        {
                            Id = 29,
                            Name = "reopened"
                        },
                        new
                        {
                            Id = 30,
                            Name = "review_dismissed"
                        },
                        new
                        {
                            Id = 31,
                            Name = "review_requested"
                        },
                        new
                        {
                            Id = 32,
                            Name = "review_request_removed"
                        },
                        new
                        {
                            Id = 33,
                            Name = "reviewed"
                        },
                        new
                        {
                            Id = 34,
                            Name = "subscribed"
                        },
                        new
                        {
                            Id = 35,
                            Name = "transferred"
                        },
                        new
                        {
                            Id = 36,
                            Name = "unassigned"
                        },
                        new
                        {
                            Id = 37,
                            Name = "unlabeled"
                        },
                        new
                        {
                            Id = 38,
                            Name = "unlocked"
                        },
                        new
                        {
                            Id = 39,
                            Name = "unmarked_as_duplicate"
                        },
                        new
                        {
                            Id = 40,
                            Name = "unpinned"
                        },
                        new
                        {
                            Id = 41,
                            Name = "unsubscribed"
                        },
                        new
                        {
                            Id = 42,
                            Name = "user_blocked"
                        });
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.Property<DateTimeOffset>("GitHubUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("ParentIssueId")
                        .HasColumnType("int");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ParentIssueId");

                    b.HasIndex("RepositoryId", "Number")
                        .IsUnique();

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.IssueEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("ActorLogin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<long>("GitHubEventId")
                        .HasColumnType("bigint");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("GitHubEventId")
                        .IsUnique();

                    b.HasIndex("IssueId");

                    b.ToTable("IssueEvents");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.IssueLabel", b =>
                {
                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("LabelId")
                        .HasColumnType("int");

                    b.HasKey("IssueId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("IssueLabels");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasDefaultValue("ededed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Name")
                        .IsUnique();

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint");

                    b.Property<string>("HtmlUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Issue", b =>
                {
                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Issue", "ParentIssue")
                        .WithMany("SubIssues")
                        .HasForeignKey("ParentIssueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Repository", "Repository")
                        .WithMany("Issues")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentIssue");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.IssueEvent", b =>
                {
                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.EventType", "EventType")
                        .WithMany("IssueEvents")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Issue", "Issue")
                        .WithMany("Events")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.IssueLabel", b =>
                {
                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Issue", "Issue")
                        .WithMany("IssueLabels")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Label", "Label")
                        .WithMany("IssueLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Label", b =>
                {
                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Repository", "Repository")
                        .WithMany("Labels")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.EventType", b =>
                {
                    b.Navigation("IssueEvents");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Issue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("IssueLabels");

                    b.Navigation("SubIssues");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Label", b =>
                {
                    b.Navigation("IssueLabels");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Repository", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
