// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Olbrasoft.GitHub.Issues.Data.EntityFrameworkCore;
using Pgvector;

#nullable disable

namespace Olbrasoft.GitHub.Issues.Migrations.PostgreSQL
{
    [DbContext(typeof(GitHubDbContext))]
    partial class GitHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("event_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "assigned"
                        },
                        new
                        {
                            Id = 2,
                            Name = "automatic_base_change_failed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "automatic_base_change_succeeded"
                        },
                        new
                        {
                            Id = 4,
                            Name = "base_ref_changed"
                        },
                        new
                        {
                            Id = 5,
                            Name = "closed"
                        },
                        new
                        {
                            Id = 6,
                            Name = "commented"
                        },
                        new
                        {
                            Id = 7,
                            Name = "committed"
                        },
                        new
                        {
                            Id = 8,
                            Name = "connected"
                        },
                        new
                        {
                            Id = 9,
                            Name = "convert_to_draft"
                        },
                        new
                        {
                            Id = 10,
                            Name = "converted_to_discussion"
                        },
                        new
                        {
                            Id = 11,
                            Name = "cross-referenced"
                        },
                        new
                        {
                            Id = 12,
                            Name = "demilestoned"
                        },
                        new
                        {
                            Id = 13,
                            Name = "deployed"
                        },
                        new
                        {
                            Id = 14,
                            Name = "deployment_environment_changed"
                        },
                        new
                        {
                            Id = 15,
                            Name = "disconnected"
                        },
                        new
                        {
                            Id = 16,
                            Name = "head_ref_deleted"
                        },
                        new
                        {
                            Id = 17,
                            Name = "head_ref_restored"
                        },
                        new
                        {
                            Id = 18,
                            Name = "head_ref_force_pushed"
                        },
                        new
                        {
                            Id = 19,
                            Name = "labeled"
                        },
                        new
                        {
                            Id = 20,
                            Name = "locked"
                        },
                        new
                        {
                            Id = 21,
                            Name = "mentioned"
                        },
                        new
                        {
                            Id = 22,
                            Name = "marked_as_duplicate"
                        },
                        new
                        {
                            Id = 23,
                            Name = "merged"
                        },
                        new
                        {
                            Id = 24,
                            Name = "milestoned"
                        },
                        new
                        {
                            Id = 25,
                            Name = "pinned"
                        },
                        new
                        {
                            Id = 26,
                            Name = "ready_for_review"
                        },
                        new
                        {
                            Id = 27,
                            Name = "referenced"
                        },
                        new
                        {
                            Id = 28,
                            Name = "renamed"
                        },
                        new
                        {
                            Id = 29,
                            Name = "reopened"
                        },
                        new
                        {
                            Id = 30,
                            Name = "review_dismissed"
                        },
                        new
                        {
                            Id = 31,
                            Name = "review_requested"
                        },
                        new
                        {
                            Id = 32,
                            Name = "review_request_removed"
                        },
                        new
                        {
                            Id = 33,
                            Name = "reviewed"
                        },
                        new
                        {
                            Id = 34,
                            Name = "subscribed"
                        },
                        new
                        {
                            Id = 35,
                            Name = "transferred"
                        },
                        new
                        {
                            Id = 36,
                            Name = "unassigned"
                        },
                        new
                        {
                            Id = 37,
                            Name = "unlabeled"
                        },
                        new
                        {
                            Id = 38,
                            Name = "unlocked"
                        },
                        new
                        {
                            Id = 39,
                            Name = "unmarked_as_duplicate"
                        },
                        new
                        {
                            Id = 40,
                            Name = "unpinned"
                        },
                        new
                        {
                            Id = 41,
                            Name = "unsubscribed"
                        },
                        new
                        {
                            Id = 42,
                            Name = "user_blocked"
                        });
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset>("GitHubUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("github_updated_at");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int?>("ParentIssueId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_issue_id");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer")
                        .HasColumnName("repository_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ParentIssueId");

                    b.HasIndex("RepositoryId", "Number")
                        .IsUnique();

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.IssueEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorLogin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_login");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("event_type_id");

                    b.Property<long>("GitHubEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_event_id");

                    b.Property<int>("IssueId")
                        .HasColumnType("integer")
                        .HasColumnName("issue_id");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("GitHubEventId")
                        .IsUnique();

                    b.HasIndex("IssueId");

                    b.ToTable("issue_events", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.IssueLabel", b =>
                {
                    b.Property<int>("IssueId")
                        .HasColumnType("integer")
                        .HasColumnName("issue_id");

                    b.Property<int>("LabelId")
                        .HasColumnType("integer")
                        .HasColumnName("label_id");

                    b.HasKey("IssueId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("issue_labels", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasDefaultValue("ededed")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer")
                        .HasColumnName("repository_id");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Name")
                        .IsUnique();

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_id");

                    b.Property<string>("HtmlUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("html_url");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Issue", b =>
                {
                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Issue", "ParentIssue")
                        .WithMany("SubIssues")
                        .HasForeignKey("ParentIssueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Repository", "Repository")
                        .WithMany("Issues")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentIssue");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.IssueEvent", b =>
                {
                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.EventType", "EventType")
                        .WithMany("IssueEvents")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Issue", "Issue")
                        .WithMany("Events")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.IssueLabel", b =>
                {
                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Issue", "Issue")
                        .WithMany("IssueLabels")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Label", "Label")
                        .WithMany("IssueLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Label", b =>
                {
                    b.HasOne("Olbrasoft.GitHub.Issues.Data.Entities.Repository", "Repository")
                        .WithMany("Labels")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.EventType", b =>
                {
                    b.Navigation("IssueEvents");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Issue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("IssueLabels");

                    b.Navigation("SubIssues");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Label", b =>
                {
                    b.Navigation("IssueLabels");
                });

            modelBuilder.Entity("Olbrasoft.GitHub.Issues.Data.Entities.Repository", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
